// <auto-generated />
using Aplikasi_Data_Kendaraan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aplikasi_Data_Kendaraan.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241028070452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aplikasi_Data_Kendaraan.backend.Models.Kendaraan", b =>
                {
                    b.Property<string>("NomorRegistrasi")
                        .HasColumnType("text");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BahanBakar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KapasitasSilinder")
                        .HasColumnType("integer");

                    b.Property<string>("MerkKendaraan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPemilik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TahunPembuatan")
                        .HasColumnType("integer");

                    b.Property<string>("WarnaKendaraan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NomorRegistrasi");

                    b.ToTable("Kendaraans");
                });
#pragma warning restore 612, 618
        }
    }
}
